# Generated by Django 4.1.3 on 2022-11-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
